baseURL = "https://monospacedmonologues.com/"
languageCode = "en-gb"
title = "Monospaced Monologues"
theme = "ananke"

paginate = 1000
summaryLength = 1048576

pygmentsCodefences = true

disqusShortname = "monospacedmonologues"

# if a tweet disappears, don't worry about it
ignoreErrors = ["error-remote-getjson"]

[permalinks]
posts = "/:year/:month/:slug/"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[menu]
  [[menu.main]]
  name = "by Samir Talwar"

[params]
rss = "/index.xml"
email = "samir@functional.computer"
mastodon = "https://mastodon.functional.computer/@samir"

date_format = "2 January, 2006"
featured_image = false
background_color_class = "bg-near-black"
post_content_classes = "avenir"
custom_css = [
  "css/site.css",
  "https://assets.monospacedmonologues.com/webfont-iosevka-11.2.4/iosevka.css",
]
assets_prefix = "https://assets.monospacedmonologues.com"
recent_posts_number = 5


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true
