baseURL = "https://monospacedmonologues.com/"
languageCode = "en-gb"
title = "Monospaced Monologues"
theme = "ananke"

paginate = 1000
summaryLength = 1048576

pygmentsCodefences = true

disqusShortname = "monospacedmonologues"

[permalinks]
posts = "/:year/:month/:slug/"

[menu]
  [[menu.main]]
  name = "by Samir Talwar"
  url = "https://noodlesandwich.com"

[params]
rss = "/index.xml"
email = "samir@noodlesandwich.com"
twitter = "https://twitter.com/SamirTalwar"
featured_image = false
background_color_class = "bg-near-black"
custom_css = ["css/site.css"]
assets_prefix = "https://assets.monospacedmonologues.com"
recent_posts_number = 5


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true
