baseURL = "https://monospacedmonologues.com/"
languageCode = "en-gb"
title = "Monospaced Monologues"
theme = "ananke"

pygmentsCodefences = true

[permalinks]
posts = "/:year/:month/:slug/"

[blackfriday]
extensionsmask = ["noIntraEmphasis"]
