baseURL = "https://monospacedmonologues.com/"
languageCode = "en-gb"
title = "Monospaced Monologues"
theme = "ananke"

pygmentsCodefences = true

disqusShortname = "monospacedmonologues"

[permalinks]
posts = "/:year/:month/:slug/"

[menu]
  [[menu.main]]
  name = "by Samir Talwar"
  url = "https://noodlesandwich.com"

[params]
twitter = "https://twitter.com/SamirTalwar"
featured_image = false
background_color_class = "bg-near-black"
custom_css = ["css/site.css"]
assets_prefix = "https://assets.monospacedmonologues.com"
recent_posts_number = 5

[blackfriday]
extensionsmask = ["noIntraEmphasis"]
