version: '3.6'

services:
  site:
    build: .
    image: samirtalwar/monospacedmonologues.com
    command:
      - 'server'
      - '--bind=0.0.0.0'
      - '--port=80'

  proxy:
    build: services/proxy
    image: samirtalwar/monospacedmonologues.com-proxy
    ports:
      - 80:80
    environment:
      SITE: http://site
