#!/bin/sh

# shellcheck disable=SC2006

set -e
set -u

compile() {
  HUGO_ENV=production \
    hugo --destination='/usr/share/nginx/html' --baseURL="$BASE_URL"
  echo "Compiled at `date -u +'%FT%TZ'`."
}

start() {
  nginx -g 'daemon off;' &
}

stop() {
  exit_status=$?
  if [ ! -e /var/run/server.pid ]; then
    return $exit_status
  fi

  kill "`cat /var/run/server.pid`"
  rm /var/run/server.pid
  return $exit_status
}

compile

trap 'stop' EXIT INT TERM
start
echo $! > /var/run/server.pid

while true; do
  for _ in `seq 1 60`; do
    sleep 1
    [ -e /var/run/server.pid ] || break
  done
  [ -e /var/run/server.pid ] || break
  compile
done
